BEGIN;

CREATE TABLE IF NOT EXISTS "Bildirimler"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TipId" integer NOT NULL,
    "Baslik" character varying(160) NOT NULL,
    "Mesaj" character varying(1000) NOT NULL,
    "HedefUrl" character varying(500) NULL,
    "ReferansTipi" character varying(80) NULL,
    "ReferansId" integer NULL,
    "OlusturanKullaniciId" integer NULL,
    "CreatedDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Istanbul'),
    "UpdatedDate" timestamp without time zone NULL,
    "CreatedBy" text NULL,
    "UpdatedBy" text NULL,
    CONSTRAINT "FK_Bildirimler_Kullanicilar_OlusturanKullaniciId"
        FOREIGN KEY ("OlusturanKullaniciId")
        REFERENCES "Kullanicilar" ("Id")
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_Bildirimler_OlusturanKullaniciId"
    ON "Bildirimler" ("OlusturanKullaniciId");

CREATE INDEX IF NOT EXISTS "IX_Bildirimler_CreatedDate"
    ON "Bildirimler" ("CreatedDate" DESC);

CREATE INDEX IF NOT EXISTS "IX_Bildirimler_TipId_CreatedDate"
    ON "Bildirimler" ("TipId", "CreatedDate" DESC);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Bildirimler_Tip_Referans"
    ON "Bildirimler" ("TipId", "ReferansTipi", "ReferansId")
    WHERE "ReferansId" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "KullaniciBildirimleri"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BildirimId" integer NOT NULL,
    "KullaniciId" integer NOT NULL,
    "OkunduMu" boolean NOT NULL DEFAULT FALSE,
    "OkunmaTarihi" timestamp without time zone NULL,
    "CreatedDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Istanbul'),
    "UpdatedDate" timestamp without time zone NULL,
    "CreatedBy" text NULL,
    "UpdatedBy" text NULL,
    CONSTRAINT "FK_KullaniciBildirimleri_Bildirimler_BildirimId"
        FOREIGN KEY ("BildirimId")
        REFERENCES "Bildirimler" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_KullaniciBildirimleri_Kullanicilar_KullaniciId"
        FOREIGN KEY ("KullaniciId")
        REFERENCES "Kullanicilar" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "AK_KullaniciBildirimleri_BildirimId_KullaniciId"
        UNIQUE ("BildirimId", "KullaniciId")
);

CREATE INDEX IF NOT EXISTS "IX_KullaniciBildirimleri_Kullanici_Okunmadi_Id"
    ON "KullaniciBildirimleri" ("KullaniciId", "OkunduMu", "Id" DESC);

CREATE INDEX IF NOT EXISTS "IX_KullaniciBildirimleri_BildirimId"
    ON "KullaniciBildirimleri" ("BildirimId");

CREATE TABLE IF NOT EXISTS "BildirimAbonelikleri"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "KullaniciId" integer NOT NULL,
    "TipId" integer NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Istanbul'),
    "UpdatedDate" timestamp without time zone NULL,
    "CreatedBy" text NULL,
    "UpdatedBy" text NULL,
    CONSTRAINT "FK_BildirimAbonelikleri_Kullanicilar_KullaniciId"
        FOREIGN KEY ("KullaniciId")
        REFERENCES "Kullanicilar" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "AK_BildirimAbonelikleri_KullaniciId_TipId"
        UNIQUE ("KullaniciId", "TipId")
);

CREATE INDEX IF NOT EXISTS "IX_BildirimAbonelikleri_TipId"
    ON "BildirimAbonelikleri" ("TipId");

COMMIT;

-- Bildirim tipleri:
-- 1 = Çeki yüklendi
-- 2 = Revizyon çekisi yüklendi
-- Alıcılar uygulamadaki Kullanıcı Yönetimi ekranından seçilebilir.
