// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _3K.Infrastructure.Data;

#nullable disable

namespace _3K.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330225611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrijinalDosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("Cekiler");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarkodNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CekiId")
                        .HasColumnType("integer");

                    b.Property<string>("CekideGecenSandikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EklemeNedeni")
                        .HasColumnType("text");

                    b.Property<string>("FiiliSandikNo")
                        .HasColumnType("text");

                    b.Property<int>("GridDurumu")
                        .HasColumnType("integer");

                    b.Property<bool>("IsManuelEklenen")
                        .HasColumnType("boolean");

                    b.Property<int>("IstenenAdet")
                        .HasColumnType("integer");

                    b.Property<int?>("KontrolEdenId")
                        .HasColumnType("integer");

                    b.Property<string>("OlcuResmiPozNo")
                        .HasColumnType("text");

                    b.Property<int?>("PaketleyenId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<int>("UcKDurumu")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiId");

                    b.HasIndex("KontrolEdenId");

                    b.HasIndex("PaketleyenId");

                    b.ToTable("CekiSatirlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.FBTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("AlinanFB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AsilFB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IadeDurumu")
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<string>("Neden")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("FBTransferleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.HareketGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferansId")
                        .HasColumnType("text");

                    b.Property<string>("ReferansTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.ToTable("HareketGecmisleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BasHarf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("_3K.Core.Entities.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FBNo")
                        .HasColumnType("text");

                    b.Property<string>("Gerilim")
                        .HasColumnType("text");

                    b.Property<string>("Guc")
                        .HasColumnType("text");

                    b.Property<string>("Lokasyon")
                        .HasColumnType("text");

                    b.Property<string>("Musteri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NakilOlcuResmiNo")
                        .HasColumnType("text");

                    b.Property<string>("OlcuResmiNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlanlananSevkTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProjeMuduru")
                        .HasColumnType("text");

                    b.Property<string>("ProjeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SonMontajResmiNo")
                        .HasColumnType("text");

                    b.Property<string>("SorumluKisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("_3K.Core.Entities.Revizyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.ToTable("Revizyonlar");
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DepoLokasyonu")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<string>("SandikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId", "SandikNo")
                        .IsUnique();

                    b.ToTable("Sandiklar");
                });

            modelBuilder.Entity("_3K.Core.Entities.SandikIcerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EksikAdet")
                        .HasColumnType("integer");

                    b.Property<int>("KonulanAdet")
                        .HasColumnType("integer");

                    b.Property<int>("SandikId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("SandikId");

                    b.ToTable("SandikIcerikleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokHareketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<int>("StokKaydiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.HasIndex("StokKaydiId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KaynakProje")
                        .HasColumnType("text");

                    b.Property<string>("Lokasyon")
                        .HasColumnType("text");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<string>("StokGirisNedeni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("StokKayitlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Cekiler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.HasOne("_3K.Core.Entities.Ceki", "Ceki")
                        .WithMany("CekiSatirlari")
                        .HasForeignKey("CekiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "KontrolEden")
                        .WithMany()
                        .HasForeignKey("KontrolEdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_3K.Core.Entities.Kullanici", "Paketleyen")
                        .WithMany()
                        .HasForeignKey("PaketleyenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ceki");

                    b.Navigation("KontrolEden");

                    b.Navigation("Paketleyen");
                });

            modelBuilder.Entity("_3K.Core.Entities.FBTransfer", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("FBTransferleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("_3K.Core.Entities.HareketGecmisi", b =>
                {
                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("HareketGecmisleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("HareketGecmisleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.Revizyon", b =>
                {
                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("Revizyonlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Revizyonlar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Sandiklar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.SandikIcerik", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("SandikIcerikleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Sandik", "Sandik")
                        .WithMany("SandikIcerikleri")
                        .HasForeignKey("SandikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Sandik");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokHareketi", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.StokKaydi", "StokKaydi")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("StokKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");

                    b.Navigation("StokKaydi");
                });

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.Navigation("CekiSatirlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.Navigation("FBTransferleri");

                    b.Navigation("SandikIcerikleri");

                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("HareketGecmisleri");

                    b.Navigation("Revizyonlar");
                });

            modelBuilder.Entity("_3K.Core.Entities.Proje", b =>
                {
                    b.Navigation("Cekiler");

                    b.Navigation("HareketGecmisleri");

                    b.Navigation("Revizyonlar");

                    b.Navigation("Sandiklar");

                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.Navigation("SandikIcerikleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokKaydi", b =>
                {
                    b.Navigation("StokHareketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
