// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _3K.Infrastructure.Data;

#nullable disable

namespace _3K.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416234624_UpdateAllStatusTagsToSpaced")]
    partial class UpdateAllStatusTagsToSpaced
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrijinalDosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("Cekiler");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarkodNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CekiId")
                        .HasColumnType("integer");

                    b.Property<string>("CekideGecenSandikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EklemeNedeni")
                        .HasColumnType("text");

                    b.Property<string>("FiiliSandikNo")
                        .HasColumnType("text");

                    b.Property<int>("GelenMiktar")
                        .HasColumnType("integer");

                    b.Property<string>("GeriGonderilmeSebebi")
                        .HasColumnType("text");

                    b.Property<string>("GridDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GridGelenAdet")
                        .HasColumnType("integer");

                    b.Property<string>("GridNotu")
                        .HasColumnType("text");

                    b.Property<int?>("GridPersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("GridSevkDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GridSevkMiktari")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GridSevkTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HataliMiktar")
                        .HasColumnType("integer");

                    b.Property<bool>("IsManuelEklenen")
                        .HasColumnType("boolean");

                    b.Property<int>("IstenenAdet")
                        .HasColumnType("integer");

                    b.Property<int>("KarsilananMiktar")
                        .HasColumnType("integer");

                    b.Property<string>("KaynakHedefProjeNo")
                        .HasColumnType("text");

                    b.Property<int?>("KaynakProjeId")
                        .HasColumnType("integer");

                    b.Property<int?>("KontrolEdenId")
                        .HasColumnType("integer");

                    b.Property<string>("OlcuResmiPozNo")
                        .HasColumnType("text");

                    b.Property<int?>("PaketleyenId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrafoSevkAdet")
                        .HasColumnType("integer");

                    b.Property<string>("UcKAciklama")
                        .HasColumnType("text");

                    b.Property<string>("UcKDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UcKKarsilamaTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UcKNotu")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiId");

                    b.HasIndex("Durum");

                    b.HasIndex("GeriGonderilmeSebebi");

                    b.HasIndex("GridDurumu");

                    b.HasIndex("GridPersonelId");

                    b.HasIndex("KaynakProjeId");

                    b.HasIndex("KontrolEdenId");

                    b.HasIndex("PaketleyenId");

                    b.HasIndex("UcKDurumu");

                    b.ToTable("CekiSatirlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.FBTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("AlinanFB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AsilFB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IadeDurumu")
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<string>("Neden")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("FBTransferleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.HareketGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferansId")
                        .HasColumnType("text");

                    b.Property<string>("ReferansTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.ToTable("HareketGecmisleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BasHarf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupDepoLokasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupDepoLokasyonlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Belirsiz"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "3K"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Seymen"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "Grid"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupGeriGonderilmeSebebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupGeriGonderilmeSebepleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Tadilat"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Iptal"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupGridDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupGridDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Bekliyor"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Üretimde"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Stok Hazır"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Sevk Edildi"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "Kısmi Sevk Edildi"
                        },
                        new
                        {
                            Id = 6,
                            Anahtar = 5,
                            Deger = "Bekletiliyor"
                        },
                        new
                        {
                            Id = 7,
                            Anahtar = 6,
                            Deger = "İptal Edildi"
                        },
                        new
                        {
                            Id = 8,
                            Anahtar = 7,
                            Deger = "Tam Geldi"
                        },
                        new
                        {
                            Id = 9,
                            Anahtar = 8,
                            Deger = "Eksik Geldi"
                        },
                        new
                        {
                            Id = 10,
                            Anahtar = 9,
                            Deger = "Gelmedi"
                        },
                        new
                        {
                            Id = 11,
                            Anahtar = 10,
                            Deger = "Trafo Sevk"
                        },
                        new
                        {
                            Id = 12,
                            Anahtar = 11,
                            Deger = "İptal"
                        },
                        new
                        {
                            Id = 13,
                            Anahtar = 12,
                            Deger = "Siparişte"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupIslemTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupIslemTipleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "CekiYuklendi"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "SandikOlusturuldu"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "SandikBolundu"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "SandikDegisti"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "UrunTasindi"
                        },
                        new
                        {
                            Id = 6,
                            Anahtar = 5,
                            Deger = "FBTransferi"
                        },
                        new
                        {
                            Id = 7,
                            Anahtar = 6,
                            Deger = "StokKullanimi"
                        },
                        new
                        {
                            Id = 8,
                            Anahtar = 7,
                            Deger = "EksikKapatildi"
                        },
                        new
                        {
                            Id = 9,
                            Anahtar = 8,
                            Deger = "PDFAlindi"
                        },
                        new
                        {
                            Id = 10,
                            Anahtar = 9,
                            Deger = "MailGonderildi"
                        },
                        new
                        {
                            Id = 11,
                            Anahtar = 10,
                            Deger = "UrunGuncellendi"
                        },
                        new
                        {
                            Id = 12,
                            Anahtar = 11,
                            Deger = "KullaniciOlusturuldu"
                        },
                        new
                        {
                            Id = 13,
                            Anahtar = 12,
                            Deger = "ProjeOlusturuldu"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupProjeDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupProjeDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Hazırlanıyor"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Devam"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Tamamlandı"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Beklemede"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "Sevk Edildi"
                        },
                        new
                        {
                            Id = 6,
                            Anahtar = 5,
                            Deger = "Eksik Sevk Edildi"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupSandikDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupSandikDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Boş"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Hazırlanıyor"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Hazır"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Sevk Edildi"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupSandikTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupSandikTipleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 1,
                            Deger = "Proje"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 2,
                            Deger = "Yedek"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 3,
                            Deger = "Saha"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupStokDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupStokDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Aktif"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Tukendi"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Rezerve"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupUcKDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupUcKDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Bekliyor"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Tam Geldi"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Eksik Geldi"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Gelmedi"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "Paketlendi"
                        },
                        new
                        {
                            Id = 6,
                            Anahtar = 5,
                            Deger = "Kontrol Edildi"
                        },
                        new
                        {
                            Id = 7,
                            Anahtar = 6,
                            Deger = "İade Edildi"
                        },
                        new
                        {
                            Id = 8,
                            Anahtar = 7,
                            Deger = "Projeden Karşılandı"
                        },
                        new
                        {
                            Id = 9,
                            Anahtar = 8,
                            Deger = "Stoktan Karşılandı"
                        },
                        new
                        {
                            Id = 10,
                            Anahtar = 9,
                            Deger = "Tedarikçiden Geldi"
                        },
                        new
                        {
                            Id = 11,
                            Anahtar = 10,
                            Deger = "Başka Projeye Verildi"
                        },
                        new
                        {
                            Id = 12,
                            Anahtar = 11,
                            Deger = "Geri Gönderildi"
                        },
                        new
                        {
                            Id = 13,
                            Anahtar = 12,
                            Deger = "Hatalı Ürün"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupUrunDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupUrunDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Bekliyor"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Kısmi Geldi"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Tamamlandı"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Eksik"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "Stoktan Karşılandı"
                        },
                        new
                        {
                            Id = 6,
                            Anahtar = 5,
                            Deger = "FB'den Karşılandı"
                        },
                        new
                        {
                            Id = 7,
                            Anahtar = 6,
                            Deger = "Sonra Gidecek"
                        },
                        new
                        {
                            Id = 8,
                            Anahtar = 7,
                            Deger = "Sandık Değişti"
                        },
                        new
                        {
                            Id = 9,
                            Anahtar = 8,
                            Deger = "İptal/Pasif"
                        },
                        new
                        {
                            Id = 10,
                            Anahtar = 9,
                            Deger = "Teslim Alındı"
                        },
                        new
                        {
                            Id = 11,
                            Anahtar = 10,
                            Deger = "Geri Gönderildi"
                        },
                        new
                        {
                            Id = 12,
                            Anahtar = 11,
                            Deger = "Kısmi Tamamlandı"
                        },
                        new
                        {
                            Id = 13,
                            Anahtar = 12,
                            Deger = "Kayıp"
                        },
                        new
                        {
                            Id = 14,
                            Anahtar = 13,
                            Deger = "Grid'de Hazır"
                        },
                        new
                        {
                            Id = 15,
                            Anahtar = 14,
                            Deger = "Grid'de Eksik"
                        },
                        new
                        {
                            Id = 16,
                            Anahtar = 15,
                            Deger = "Siparişte"
                        },
                        new
                        {
                            Id = 17,
                            Anahtar = 16,
                            Deger = "Gelmedi"
                        },
                        new
                        {
                            Id = 18,
                            Anahtar = 17,
                            Deger = "Trafo Sevk"
                        },
                        new
                        {
                            Id = 19,
                            Anahtar = 18,
                            Deger = "Başka Projeye Verildi"
                        },
                        new
                        {
                            Id = 20,
                            Anahtar = 19,
                            Deger = "Hatalı Ürün"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupYetkiTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupYetkiTipleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "N"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "R"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "W"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.MenuTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("MenuTanimlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(4628),
                            Icon = "ri-dashboard-line",
                            Kod = "dashboard",
                            LabelKey = "MENU.DASHBOARD",
                            Route = "/dashboard",
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5424),
                            Icon = "ri-folder-line",
                            Kod = "projeler",
                            LabelKey = "MENU.PROJELER",
                            Sira = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5434),
                            Icon = "ri-archive-line",
                            Kod = "sandik-yonetimi",
                            LabelKey = "MENU.SANDIK_YONETIMI",
                            Route = "/sandik-yonetimi",
                            Sira = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5437),
                            Icon = "ri-error-warning-line",
                            Kod = "eksik-listesi",
                            LabelKey = "MENU.EKSIK_LISTESI",
                            Route = "/eksik-listesi",
                            Sira = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5438),
                            Icon = "ri-building-2-line",
                            Kod = "depo-durumu",
                            LabelKey = "MENU.DEPO_DURUMU",
                            Route = "/depo-durumu",
                            Sira = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5439),
                            Icon = "ri-arrow-left-right-line",
                            Kod = "fb-transfer",
                            LabelKey = "MENU.FB_TRANSFER",
                            Route = "/fb-transfer",
                            Sira = 6
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5440),
                            Icon = "ri-stack-line",
                            Kod = "stok",
                            LabelKey = "MENU.STOK_MODULU",
                            Route = "/stok",
                            Sira = 7
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5442),
                            Icon = "ri-tools-line",
                            Kod = "saha-malzeme",
                            LabelKey = "MENU.SAHA_MALZEMESI",
                            Route = "/saha-malzeme",
                            Sira = 8
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5443),
                            Icon = "ri-history-line",
                            Kod = "hareket-gecmisi",
                            LabelKey = "MENU.HAREKET_GECMISI",
                            Route = "/hareket-gecmisi",
                            Sira = 9
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5444),
                            Icon = "ri-user-settings-line",
                            Kod = "kullanicilar",
                            LabelKey = "MENU.KULLANICI_YETKI",
                            Route = "/kullanicilar",
                            Sira = 10
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5445),
                            Icon = "ri-shield-user-line",
                            Kod = "rol-yonetimi",
                            LabelKey = "MENU.ROL_YONETIMI",
                            Route = "/rol-yonetimi",
                            Sira = 11
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5535),
                            Icon = "",
                            Kod = "aktif-projeler",
                            LabelKey = "MENU.AKTIF_PROJELER",
                            ParentId = 2,
                            Route = "/projeler",
                            Sira = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5536),
                            Icon = "",
                            Kod = "sevk-edilen",
                            LabelKey = "MENU.SEVK_EDILEN",
                            ParentId = 2,
                            Route = "/projeler/sevk-edilen",
                            Sira = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5537),
                            Icon = "",
                            Kod = "grid-modulu",
                            LabelKey = "MENU.GRID_MODULU",
                            ParentId = 2,
                            Sira = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5539),
                            Icon = "",
                            Kod = "3k-modulu",
                            LabelKey = "MENU.3K_MODULU",
                            ParentId = 2,
                            Sira = 4
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FBNo")
                        .HasColumnType("text");

                    b.Property<string>("Gerilim")
                        .HasColumnType("text");

                    b.Property<string>("Guc")
                        .HasColumnType("text");

                    b.Property<string>("Lokasyon")
                        .HasColumnType("text");

                    b.Property<string>("Musteri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NakilOlcuResmiNo")
                        .HasColumnType("text");

                    b.Property<string>("OlcuResmiNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlanlananSevkTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProjeMuduru")
                        .HasColumnType("text");

                    b.Property<string>("ProjeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SonMontajResmiNo")
                        .HasColumnType("text");

                    b.Property<string>("SorumluKisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("_3K.Core.Entities.ProjeTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("BarkodNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("HedefCekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<int>("HedefProjeId")
                        .HasColumnType("integer");

                    b.Property<int>("KaynakCekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<int>("KaynakProjeId")
                        .HasColumnType("integer");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("HedefCekiSatiriId");

                    b.HasIndex("HedefProjeId");

                    b.HasIndex("KaynakCekiSatiriId");

                    b.HasIndex("KaynakProjeId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("ProjeTransferleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Revizyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.ToTable("Revizyonlar");
                });

            modelBuilder.Entity("_3K.Core.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Personel3K",
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(4153)
                        },
                        new
                        {
                            Id = 3,
                            Ad = "PersonelGrid",
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(4154)
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Yonetici",
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(4155)
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.RolYetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MenuTanimiId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YetkiTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MenuTanimiId");

                    b.HasIndex("YetkiTipi");

                    b.HasIndex("RolId", "MenuTanimiId")
                        .IsUnique();

                    b.ToTable("RolYetkileri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(5744),
                            MenuTanimiId = 1,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6077),
                            MenuTanimiId = 2,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6078),
                            MenuTanimiId = 3,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6079),
                            MenuTanimiId = 4,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6079),
                            MenuTanimiId = 5,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6080),
                            MenuTanimiId = 6,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6081),
                            MenuTanimiId = 7,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6081),
                            MenuTanimiId = 8,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6081),
                            MenuTanimiId = 9,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6082),
                            MenuTanimiId = 10,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6083),
                            MenuTanimiId = 11,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6083),
                            MenuTanimiId = 12,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6084),
                            MenuTanimiId = 13,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6084),
                            MenuTanimiId = 14,
                            RolId = 1,
                            YetkiTipi = "W"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 4, 16, 23, 46, 23, 852, DateTimeKind.Utc).AddTicks(6084),
                            MenuTanimiId = 15,
                            RolId = 1,
                            YetkiTipi = "W"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepoLokasyonu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<string>("SandikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepoLokasyonu");

                    b.HasIndex("Durum");

                    b.HasIndex("Tip");

                    b.HasIndex("ProjeId", "SandikNo")
                        .IsUnique();

                    b.ToTable("Sandiklar");
                });

            modelBuilder.Entity("_3K.Core.Entities.SandikIcerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EksikAdet")
                        .HasColumnType("integer");

                    b.Property<int>("KonulanAdet")
                        .HasColumnType("integer");

                    b.Property<int>("SandikId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("SandikId");

                    b.ToTable("SandikIcerikleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokHareketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<int>("StokKaydiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("IslemTipi");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.HasIndex("StokKaydiId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KaynakProje")
                        .HasColumnType("text");

                    b.Property<string>("Lokasyon")
                        .HasColumnType("text");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<string>("StokGirisNedeni")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.ToTable("StokKayitlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Cekiler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.HasOne("_3K.Core.Entities.Ceki", "Ceki")
                        .WithMany("CekiSatirlari")
                        .HasForeignKey("CekiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupUrunDurum", null)
                        .WithMany()
                        .HasForeignKey("Durum")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupGeriGonderilmeSebebi", null)
                        .WithMany()
                        .HasForeignKey("GeriGonderilmeSebebi")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_3K.Core.Entities.LookupGridDurum", null)
                        .WithMany()
                        .HasForeignKey("GridDurumu")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "GridPersonel")
                        .WithMany()
                        .HasForeignKey("GridPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_3K.Core.Entities.Proje", "KaynakProje")
                        .WithMany()
                        .HasForeignKey("KaynakProjeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_3K.Core.Entities.Kullanici", "KontrolEden")
                        .WithMany()
                        .HasForeignKey("KontrolEdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_3K.Core.Entities.Kullanici", "Paketleyen")
                        .WithMany()
                        .HasForeignKey("PaketleyenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_3K.Core.Entities.LookupUcKDurum", null)
                        .WithMany()
                        .HasForeignKey("UcKDurumu")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ceki");

                    b.Navigation("GridPersonel");

                    b.Navigation("KaynakProje");

                    b.Navigation("KontrolEden");

                    b.Navigation("Paketleyen");
                });

            modelBuilder.Entity("_3K.Core.Entities.FBTransfer", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("FBTransferleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("_3K.Core.Entities.HareketGecmisi", b =>
                {
                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("HareketGecmisleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("HareketGecmisleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.Kullanici", b =>
                {
                    b.HasOne("_3K.Core.Entities.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("_3K.Core.Entities.MenuTanimi", b =>
                {
                    b.HasOne("_3K.Core.Entities.MenuTanimi", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("_3K.Core.Entities.Proje", b =>
                {
                    b.HasOne("_3K.Core.Entities.LookupProjeDurum", null)
                        .WithMany()
                        .HasForeignKey("Durum")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_3K.Core.Entities.ProjeTransfer", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "HedefCekiSatiri")
                        .WithMany()
                        .HasForeignKey("HedefCekiSatiriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_3K.Core.Entities.Proje", "HedefProje")
                        .WithMany()
                        .HasForeignKey("HedefProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.CekiSatiri", "KaynakCekiSatiri")
                        .WithMany()
                        .HasForeignKey("KaynakCekiSatiriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "KaynakProje")
                        .WithMany()
                        .HasForeignKey("KaynakProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HedefCekiSatiri");

                    b.Navigation("HedefProje");

                    b.Navigation("KaynakCekiSatiri");

                    b.Navigation("KaynakProje");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("_3K.Core.Entities.Revizyon", b =>
                {
                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("Revizyonlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Revizyonlar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.RolYetki", b =>
                {
                    b.HasOne("_3K.Core.Entities.MenuTanimi", "MenuTanimi")
                        .WithMany("Yetkiler")
                        .HasForeignKey("MenuTanimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Rol", "Rol")
                        .WithMany("Yetkiler")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupYetkiTipi", null)
                        .WithMany()
                        .HasForeignKey("YetkiTipi")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuTanimi");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.HasOne("_3K.Core.Entities.LookupDepoLokasyon", null)
                        .WithMany()
                        .HasForeignKey("DepoLokasyonu")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupSandikDurum", null)
                        .WithMany()
                        .HasForeignKey("Durum")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Sandiklar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupSandikTipi", null)
                        .WithMany()
                        .HasForeignKey("Tip")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.SandikIcerik", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("SandikIcerikleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Sandik", "Sandik")
                        .WithMany("SandikIcerikleri")
                        .HasForeignKey("SandikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Sandik");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokHareketi", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupIslemTipi", null)
                        .WithMany()
                        .HasForeignKey("IslemTipi")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.StokKaydi", "StokKaydi")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("StokKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");

                    b.Navigation("StokKaydi");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokKaydi", b =>
                {
                    b.HasOne("_3K.Core.Entities.LookupStokDurum", null)
                        .WithMany()
                        .HasForeignKey("Durum")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.Navigation("CekiSatirlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.Navigation("FBTransferleri");

                    b.Navigation("SandikIcerikleri");

                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("HareketGecmisleri");

                    b.Navigation("Revizyonlar");
                });

            modelBuilder.Entity("_3K.Core.Entities.MenuTanimi", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Yetkiler");
                });

            modelBuilder.Entity("_3K.Core.Entities.Proje", b =>
                {
                    b.Navigation("Cekiler");

                    b.Navigation("HareketGecmisleri");

                    b.Navigation("Revizyonlar");

                    b.Navigation("Sandiklar");

                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Rol", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("Yetkiler");
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.Navigation("SandikIcerikleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokKaydi", b =>
                {
                    b.Navigation("StokHareketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
