// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _3K.Infrastructure.Data;

#nullable disable

namespace _3K.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrijinalDosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("Cekiler");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarkodNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CekiId")
                        .HasColumnType("integer");

                    b.Property<string>("CekideGecenSandikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EklemeNedeni")
                        .HasColumnType("text");

                    b.Property<string>("FiiliSandikNo")
                        .HasColumnType("text");

                    b.Property<string>("GridDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsManuelEklenen")
                        .HasColumnType("boolean");

                    b.Property<int>("IstenenAdet")
                        .HasColumnType("integer");

                    b.Property<int?>("KontrolEdenId")
                        .HasColumnType("integer");

                    b.Property<string>("OlcuResmiPozNo")
                        .HasColumnType("text");

                    b.Property<int?>("PaketleyenId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<string>("UcKDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiId");

                    b.HasIndex("Durum");

                    b.HasIndex("GridDurumu");

                    b.HasIndex("KontrolEdenId");

                    b.HasIndex("PaketleyenId");

                    b.HasIndex("UcKDurumu");

                    b.ToTable("CekiSatirlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.FBTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("AlinanFB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AsilFB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IadeDurumu")
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<string>("Neden")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("FBTransferleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.HareketGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferansId")
                        .HasColumnType("text");

                    b.Property<string>("ReferansTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.ToTable("HareketGecmisleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BasHarf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Rol");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupDepoLokasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupDepoLokasyonlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Belirsiz"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Grid"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "UcK"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Protest"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupGridDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupGridDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Bekliyor"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Geldi"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Gelmedi"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "SevkEdildi"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupIslemTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupIslemTipleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "CekiYuklendi"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "SandikOlusturuldu"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "SandikBolundu"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "SandikDegisti"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "UrunTasindi"
                        },
                        new
                        {
                            Id = 6,
                            Anahtar = 5,
                            Deger = "FBTransferi"
                        },
                        new
                        {
                            Id = 7,
                            Anahtar = 6,
                            Deger = "StokKullanimi"
                        },
                        new
                        {
                            Id = 8,
                            Anahtar = 7,
                            Deger = "EksikKapatildi"
                        },
                        new
                        {
                            Id = 9,
                            Anahtar = 8,
                            Deger = "PDFAlindi"
                        },
                        new
                        {
                            Id = 10,
                            Anahtar = 9,
                            Deger = "MailGonderildi"
                        },
                        new
                        {
                            Id = 11,
                            Anahtar = 10,
                            Deger = "UrunGuncellendi"
                        },
                        new
                        {
                            Id = 12,
                            Anahtar = 11,
                            Deger = "KullaniciOlusturuldu"
                        },
                        new
                        {
                            Id = 13,
                            Anahtar = 12,
                            Deger = "ProjeOlusturuldu"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupKullaniciRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupKullaniciRolleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Personel3K"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "PersonelGrid"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Yonetici"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupProjeDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupProjeDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Hazirlaniyor"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Devam"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Tamamlandi"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Beklemede"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "SevkEdildi"
                        },
                        new
                        {
                            Id = 6,
                            Anahtar = 5,
                            Deger = "EksikSevkEdildi"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupSandikDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupSandikDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Bos"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Hazirlaniyor"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Hazir"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Sevkedildi"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupSandikTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupSandikTipleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 1,
                            Deger = "Proje"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 2,
                            Deger = "Yedek"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 3,
                            Deger = "Saha"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupStokDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupStokDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Aktif"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "Tukendi"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Rezerve"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupUcKDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupUcKDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Bekliyor"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "TamGeldi"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "EksikGeldi"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Gelmedi"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.LookupUrunDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anahtar")
                        .HasColumnType("integer");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupUrunDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = 0,
                            Deger = "Bekliyor"
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = 1,
                            Deger = "KismiGeldi"
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = 2,
                            Deger = "Tamamlandi"
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = 3,
                            Deger = "Eksik"
                        },
                        new
                        {
                            Id = 5,
                            Anahtar = 4,
                            Deger = "StoktanKarsilandi"
                        },
                        new
                        {
                            Id = 6,
                            Anahtar = 5,
                            Deger = "FBdenKarsilandi"
                        },
                        new
                        {
                            Id = 7,
                            Anahtar = 6,
                            Deger = "SonraGidecek"
                        },
                        new
                        {
                            Id = 8,
                            Anahtar = 7,
                            Deger = "SandikDegisti"
                        },
                        new
                        {
                            Id = 9,
                            Anahtar = 8,
                            Deger = "IptalVeyaPasif"
                        },
                        new
                        {
                            Id = 10,
                            Anahtar = 9,
                            Deger = "TeslimAlindi"
                        },
                        new
                        {
                            Id = 11,
                            Anahtar = 10,
                            Deger = "GeriGonderildi"
                        });
                });

            modelBuilder.Entity("_3K.Core.Entities.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FBNo")
                        .HasColumnType("text");

                    b.Property<string>("Gerilim")
                        .HasColumnType("text");

                    b.Property<string>("Guc")
                        .HasColumnType("text");

                    b.Property<string>("Lokasyon")
                        .HasColumnType("text");

                    b.Property<string>("Musteri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NakilOlcuResmiNo")
                        .HasColumnType("text");

                    b.Property<string>("OlcuResmiNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlanlananSevkTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProjeMuduru")
                        .HasColumnType("text");

                    b.Property<string>("ProjeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SonMontajResmiNo")
                        .HasColumnType("text");

                    b.Property<string>("SorumluKisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("_3K.Core.Entities.Revizyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.ToTable("Revizyonlar");
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepoLokasyonu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<string>("SandikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepoLokasyonu");

                    b.HasIndex("Durum");

                    b.HasIndex("Tip");

                    b.HasIndex("ProjeId", "SandikNo")
                        .IsUnique();

                    b.ToTable("Sandiklar");
                });

            modelBuilder.Entity("_3K.Core.Entities.SandikIcerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EksikAdet")
                        .HasColumnType("integer");

                    b.Property<int>("KonulanAdet")
                        .HasColumnType("integer");

                    b.Property<int>("SandikId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("SandikId");

                    b.ToTable("SandikIcerikleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokHareketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CekiSatiriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<int>("StokKaydiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekiSatiriId");

                    b.HasIndex("IslemTipi");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ProjeId");

                    b.HasIndex("StokKaydiId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KaynakProje")
                        .HasColumnType("text");

                    b.Property<string>("Lokasyon")
                        .HasColumnType("text");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<string>("StokGirisNedeni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.ToTable("StokKayitlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Cekiler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.HasOne("_3K.Core.Entities.Ceki", "Ceki")
                        .WithMany("CekiSatirlari")
                        .HasForeignKey("CekiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupUrunDurum", null)
                        .WithMany()
                        .HasForeignKey("Durum")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupGridDurum", null)
                        .WithMany()
                        .HasForeignKey("GridDurumu")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "KontrolEden")
                        .WithMany()
                        .HasForeignKey("KontrolEdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_3K.Core.Entities.Kullanici", "Paketleyen")
                        .WithMany()
                        .HasForeignKey("PaketleyenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_3K.Core.Entities.LookupUcKDurum", null)
                        .WithMany()
                        .HasForeignKey("UcKDurumu")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ceki");

                    b.Navigation("KontrolEden");

                    b.Navigation("Paketleyen");
                });

            modelBuilder.Entity("_3K.Core.Entities.FBTransfer", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("FBTransferleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("_3K.Core.Entities.HareketGecmisi", b =>
                {
                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("HareketGecmisleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("HareketGecmisleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.Kullanici", b =>
                {
                    b.HasOne("_3K.Core.Entities.LookupKullaniciRol", null)
                        .WithMany()
                        .HasForeignKey("Rol")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_3K.Core.Entities.Proje", b =>
                {
                    b.HasOne("_3K.Core.Entities.LookupProjeDurum", null)
                        .WithMany()
                        .HasForeignKey("Durum")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_3K.Core.Entities.Revizyon", b =>
                {
                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("Revizyonlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Revizyonlar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.HasOne("_3K.Core.Entities.LookupDepoLokasyon", null)
                        .WithMany()
                        .HasForeignKey("DepoLokasyonu")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupSandikDurum", null)
                        .WithMany()
                        .HasForeignKey("Durum")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("Sandiklar")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupSandikTipi", null)
                        .WithMany()
                        .HasForeignKey("Tip")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("_3K.Core.Entities.SandikIcerik", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("SandikIcerikleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Sandik", "Sandik")
                        .WithMany("SandikIcerikleri")
                        .HasForeignKey("SandikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Sandik");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokHareketi", b =>
                {
                    b.HasOne("_3K.Core.Entities.CekiSatiri", "CekiSatiri")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("CekiSatiriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.LookupIslemTipi", null)
                        .WithMany()
                        .HasForeignKey("IslemTipi")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.Proje", "Proje")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3K.Core.Entities.StokKaydi", "StokKaydi")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("StokKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CekiSatiri");

                    b.Navigation("Kullanici");

                    b.Navigation("Proje");

                    b.Navigation("StokKaydi");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokKaydi", b =>
                {
                    b.HasOne("_3K.Core.Entities.LookupStokDurum", null)
                        .WithMany()
                        .HasForeignKey("Durum")
                        .HasPrincipalKey("Deger")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_3K.Core.Entities.Ceki", b =>
                {
                    b.Navigation("CekiSatirlari");
                });

            modelBuilder.Entity("_3K.Core.Entities.CekiSatiri", b =>
                {
                    b.Navigation("FBTransferleri");

                    b.Navigation("SandikIcerikleri");

                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("HareketGecmisleri");

                    b.Navigation("Revizyonlar");
                });

            modelBuilder.Entity("_3K.Core.Entities.Proje", b =>
                {
                    b.Navigation("Cekiler");

                    b.Navigation("HareketGecmisleri");

                    b.Navigation("Revizyonlar");

                    b.Navigation("Sandiklar");

                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.Sandik", b =>
                {
                    b.Navigation("SandikIcerikleri");
                });

            modelBuilder.Entity("_3K.Core.Entities.StokKaydi", b =>
                {
                    b.Navigation("StokHareketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
