START TRANSACTION;
CREATE TABLE "FinansDuzenliIsleri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsAdi" text NOT NULL,
    "IsTuru" text NOT NULL,
    "Musteri" text NOT NULL,
    "Aciklama" text,
    "TekrarSikligi" text NOT NULL,
    "BaslangicTarihi" timestamp without time zone NOT NULL,
    "BitisTarihi" timestamp without time zone,
    "OlusturmaGunu" integer NOT NULL,
    "Aktif" boolean NOT NULL,
    "SonOlusturulanDonem" timestamp without time zone,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansDuzenliIsleri" PRIMARY KEY ("Id")
);

CREATE TABLE "FinansGiderKategorileri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Ad" text NOT NULL,
    "Aktif" boolean NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansGiderKategorileri" PRIMARY KEY ("Id")
);

CREATE TABLE "FinansIslemGecmisleri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReferansTipi" text NOT NULL,
    "ReferansId" integer NOT NULL,
    "Islem" text NOT NULL,
    "EskiDeger" text,
    "YeniDeger" text,
    "Aciklama" text,
    "IslemTarihi" timestamp without time zone NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansIslemGecmisleri" PRIMARY KEY ("Id")
);

CREATE TABLE "FinansSiparisleri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KayitNo" text NOT NULL,
    "ProjeId" integer,
    "AnaProjeNo" text NOT NULL,
    "PoNumarasi" text NOT NULL,
    "SiparisTarihi" timestamp without time zone NOT NULL,
    "Aciklama" text,
    "Durum" integer NOT NULL,
    "IptalTarihi" timestamp without time zone,
    "IptalAciklamasi" text,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansSiparisleri" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinansSiparisleri_Projeler_ProjeId" FOREIGN KEY ("ProjeId") REFERENCES "Projeler" ("Id") ON DELETE SET NULL
);

CREATE TABLE "FinansOzelIsleri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KayitNo" text NOT NULL,
    "IsTuru" text NOT NULL,
    "Musteri" text NOT NULL,
    "ProjeId" integer,
    "IsAdi" text NOT NULL,
    "Aciklama" text,
    "Miktar" numeric(18,4) NOT NULL,
    "Birim" text NOT NULL,
    "IsTarihi" timestamp without time zone NOT NULL,
    "DuzenliIsId" integer,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansOzelIsleri" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinansOzelIsleri_FinansDuzenliIsleri_DuzenliIsId" FOREIGN KEY ("DuzenliIsId") REFERENCES "FinansDuzenliIsleri" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_FinansOzelIsleri_Projeler_ProjeId" FOREIGN KEY ("ProjeId") REFERENCES "Projeler" ("Id") ON DELETE SET NULL
);

CREATE TABLE "FinansGiderleri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Tarih" timestamp without time zone NOT NULL,
    "KategoriId" integer NOT NULL,
    "AltKategori" text,
    "FirmaVeyaKisi" text,
    "Aciklama" text NOT NULL,
    "Tutar" numeric(18,2) NOT NULL,
    "KdvDahil" boolean NOT NULL,
    "KdvOrani" numeric(5,2) NOT NULL,
    "ToplamTutar" numeric(18,2) NOT NULL,
    "ProjeId" integer,
    "IsTuru" integer,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansGiderleri" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinansGiderleri_FinansGiderKategorileri_KategoriId" FOREIGN KEY ("KategoriId") REFERENCES "FinansGiderKategorileri" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FinansGiderleri_Projeler_ProjeId" FOREIGN KEY ("ProjeId") REFERENCES "Projeler" ("Id") ON DELETE SET NULL
);

CREATE TABLE "FinansFaturalari" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KayitNo" text NOT NULL,
    "SiparisId" integer NOT NULL,
    "FaturaNumarasi" text NOT NULL,
    "FaturaTarihi" timestamp without time zone NOT NULL,
    "Aciklama" text,
    "Durum" integer NOT NULL,
    "IptalTarihi" timestamp without time zone,
    "IptalAciklamasi" text,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansFaturalari" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinansFaturalari_FinansSiparisleri_SiparisId" FOREIGN KEY ("SiparisId") REFERENCES "FinansSiparisleri" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "FinansIsKayitlari" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjeId" integer,
    "OzelIsId" integer,
    "KaynakKayitId" integer,
    "KaynakModul" text NOT NULL,
    "ProjeNo" text NOT NULL,
    "Musteri" text NOT NULL,
    "SandikNo" text NOT NULL,
    "SandikAdi" text NOT NULL,
    "IsTuru" integer NOT NULL,
    "Adet" numeric(18,4) NOT NULL,
    "BirimM3" numeric(18,6) NOT NULL,
    "UretimeAlinmaTarihi" timestamp without time zone NOT NULL,
    "UretimTamamlanmaTarihi" timestamp without time zone,
    "UretimDurumu" text NOT NULL,
    "AktarimTarihi" timestamp without time zone NOT NULL,
    "KaynakAktif" boolean NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansIsKayitlari" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinansIsKayitlari_FinansOzelIsleri_OzelIsId" FOREIGN KEY ("OzelIsId") REFERENCES "FinansOzelIsleri" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FinansIsKayitlari_Projeler_ProjeId" FOREIGN KEY ("ProjeId") REFERENCES "Projeler" ("Id") ON DELETE SET NULL
);

CREATE TABLE "FinansBelgeleri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BelgeTuru" integer NOT NULL,
    "SiparisId" integer,
    "FaturaId" integer,
    "OzelIsId" integer,
    "GiderId" integer,
    "DosyaAdi" text NOT NULL,
    "DosyaYolu" text NOT NULL,
    "IcerikTuru" text NOT NULL,
    "Boyut" bigint NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansBelgeleri" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinansBelgeleri_FinansFaturalari_FaturaId" FOREIGN KEY ("FaturaId") REFERENCES "FinansFaturalari" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FinansBelgeleri_FinansGiderleri_GiderId" FOREIGN KEY ("GiderId") REFERENCES "FinansGiderleri" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FinansBelgeleri_FinansOzelIsleri_OzelIsId" FOREIGN KEY ("OzelIsId") REFERENCES "FinansOzelIsleri" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FinansBelgeleri_FinansSiparisleri_SiparisId" FOREIGN KEY ("SiparisId") REFERENCES "FinansSiparisleri" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "FinansSiparisKalemleri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SiparisId" integer NOT NULL,
    "IsKaydiId" integer NOT NULL,
    "Adet" numeric(18,4) NOT NULL,
    "M3" numeric(18,6) NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansSiparisKalemleri" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinansSiparisKalemleri_FinansIsKayitlari_IsKaydiId" FOREIGN KEY ("IsKaydiId") REFERENCES "FinansIsKayitlari" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FinansSiparisKalemleri_FinansSiparisleri_SiparisId" FOREIGN KEY ("SiparisId") REFERENCES "FinansSiparisleri" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "FinansFaturaKalemleri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FaturaId" integer NOT NULL,
    "SiparisKalemiId" integer NOT NULL,
    "Adet" numeric(18,4) NOT NULL,
    "M3" numeric(18,6) NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansFaturaKalemleri" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FinansFaturaKalemleri_FinansFaturalari_FaturaId" FOREIGN KEY ("FaturaId") REFERENCES "FinansFaturalari" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FinansFaturaKalemleri_FinansSiparisKalemleri_SiparisKalemiId" FOREIGN KEY ("SiparisKalemiId") REFERENCES "FinansSiparisKalemleri" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_FinansBelgeleri_FaturaId" ON "FinansBelgeleri" ("FaturaId");

CREATE INDEX "IX_FinansBelgeleri_GiderId" ON "FinansBelgeleri" ("GiderId");

CREATE INDEX "IX_FinansBelgeleri_OzelIsId" ON "FinansBelgeleri" ("OzelIsId");

CREATE INDEX "IX_FinansBelgeleri_SiparisId" ON "FinansBelgeleri" ("SiparisId");

CREATE UNIQUE INDEX "IX_FinansFaturaKalemleri_FaturaId_SiparisKalemiId" ON "FinansFaturaKalemleri" ("FaturaId", "SiparisKalemiId");

CREATE INDEX "IX_FinansFaturaKalemleri_SiparisKalemiId" ON "FinansFaturaKalemleri" ("SiparisKalemiId");

CREATE INDEX "IX_FinansFaturalari_FaturaNumarasi" ON "FinansFaturalari" ("FaturaNumarasi");

CREATE UNIQUE INDEX "IX_FinansFaturalari_KayitNo" ON "FinansFaturalari" ("KayitNo");

CREATE INDEX "IX_FinansFaturalari_SiparisId" ON "FinansFaturalari" ("SiparisId");

CREATE UNIQUE INDEX "IX_FinansGiderKategorileri_Ad" ON "FinansGiderKategorileri" ("Ad");

CREATE INDEX "IX_FinansGiderleri_KategoriId" ON "FinansGiderleri" ("KategoriId");

CREATE INDEX "IX_FinansGiderleri_ProjeId" ON "FinansGiderleri" ("ProjeId");

CREATE UNIQUE INDEX "IX_FinansIsKayitlari_KaynakModul_KaynakKayitId" ON "FinansIsKayitlari" ("KaynakModul", "KaynakKayitId") WHERE "KaynakKayitId" IS NOT NULL;

CREATE UNIQUE INDEX "IX_FinansIsKayitlari_OzelIsId" ON "FinansIsKayitlari" ("OzelIsId");

CREATE INDEX "IX_FinansIsKayitlari_ProjeId_IsTuru" ON "FinansIsKayitlari" ("ProjeId", "IsTuru");

CREATE INDEX "IX_FinansIslemGecmisleri_ReferansTipi_ReferansId_IslemTarihi" ON "FinansIslemGecmisleri" ("ReferansTipi", "ReferansId", "IslemTarihi");

CREATE INDEX "IX_FinansOzelIsleri_DuzenliIsId" ON "FinansOzelIsleri" ("DuzenliIsId");

CREATE UNIQUE INDEX "IX_FinansOzelIsleri_KayitNo" ON "FinansOzelIsleri" ("KayitNo");

CREATE INDEX "IX_FinansOzelIsleri_ProjeId" ON "FinansOzelIsleri" ("ProjeId");

CREATE INDEX "IX_FinansSiparisKalemleri_IsKaydiId" ON "FinansSiparisKalemleri" ("IsKaydiId");

CREATE UNIQUE INDEX "IX_FinansSiparisKalemleri_SiparisId_IsKaydiId" ON "FinansSiparisKalemleri" ("SiparisId", "IsKaydiId");

CREATE UNIQUE INDEX "IX_FinansSiparisleri_KayitNo" ON "FinansSiparisleri" ("KayitNo");

CREATE INDEX "IX_FinansSiparisleri_PoNumarasi" ON "FinansSiparisleri" ("PoNumarasi");

CREATE INDEX "IX_FinansSiparisleri_ProjeId" ON "FinansSiparisleri" ("ProjeId");

INSERT INTO "MenuTanimlari" ("Id", "Icon", "Kod", "LabelKey", "ParentId", "Route", "Sira", "CreatedDate")
SELECT 47, 'ri-bank-card-line', 'finans-yonetimi', 'MENU.FINANS_YONETIMI', NULL, '/finans-yonetimi', 9, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
        SELECT 1 FROM "MenuTanimlari" WHERE "Kod" = 'finans-yonetimi'
);

INSERT INTO "RolYetkileri" ("Id", "MenuTanimiId", "RolId", "YetkiTipiId", "CreatedDate")
SELECT 43, menu."Id", 1, 3, CURRENT_TIMESTAMP
FROM "MenuTanimlari" AS menu
WHERE menu."Kod" = 'finans-yonetimi'
    AND NOT EXISTS (
            SELECT 1
            FROM "RolYetkileri" AS yetki
            WHERE yetki."RolId" = 1 AND yetki."MenuTanimiId" = menu."Id"
    );

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260715102618_FinansSiparisTakipModulu', '10.0.0-preview.2.25163.8');

DROP INDEX "IX_FinansOzelIsleri_DuzenliIsId";

ALTER TABLE "FinansOzelIsleri" ADD "DonemAnahtari" text;

ALTER TABLE "FinansOzelIsleri" ADD "IptalAciklamasi" text;

ALTER TABLE "FinansOzelIsleri" ADD "IptalEdildi" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "FinansOzelIsleri" ADD "IptalTarihi" timestamp without time zone;

ALTER TABLE "FinansGiderleri" ADD "IptalAciklamasi" text;

ALTER TABLE "FinansGiderleri" ADD "IptalEdildi" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "FinansGiderleri" ADD "IptalTarihi" timestamp without time zone;

ALTER TABLE "FinansGiderleri" ADD "KdvTutari" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "FinansGiderleri" ADD "Matrah" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "FinansDuzenliIsleri" ADD "Birim" text NOT NULL DEFAULT '';

ALTER TABLE "FinansDuzenliIsleri" ADD "Miktar" numeric(18,4) NOT NULL DEFAULT 0.0;

ALTER TABLE "FinansDuzenliIsleri" ADD "ProjeId" integer;

ALTER TABLE "FinansBelgeleri" ADD "DosyaUzantisi" text NOT NULL DEFAULT '';

ALTER TABLE "FinansBelgeleri" ADD "SaklananDosyaAdi" text NOT NULL DEFAULT '';

ALTER TABLE "FinansBelgeleri" ADD "YukleyenKullanici" text NOT NULL DEFAULT '';

CREATE TABLE "FinansIsTuruTanimlari" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Ad" character varying(120) NOT NULL,
    "Aktif" boolean NOT NULL,
    "Sira" integer NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_FinansIsTuruTanimlari" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_FinansOzelIsleri_DuzenliIsId_DonemAnahtari" ON "FinansOzelIsleri" ("DuzenliIsId", "DonemAnahtari") WHERE "DuzenliIsId" IS NOT NULL AND "DonemAnahtari" IS NOT NULL;

CREATE INDEX "IX_FinansDuzenliIsleri_ProjeId" ON "FinansDuzenliIsleri" ("ProjeId");

CREATE UNIQUE INDEX "IX_FinansIsTuruTanimlari_Ad" ON "FinansIsTuruTanimlari" ("Ad");

ALTER TABLE "FinansDuzenliIsleri" ADD CONSTRAINT "FK_FinansDuzenliIsleri_Projeler_ProjeId" FOREIGN KEY ("ProjeId") REFERENCES "Projeler" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260715114822_FinansDonemVeIsTuruButunlugu', '10.0.0-preview.2.25163.8');

COMMIT;

