/*
    Onaya gönderilen çeki revizyonlarının dosyasını ve talep anındaki güvenli
    ön izleme snapshot'ını değişmez bir artifact olarak saklar.

    Rol ataması bu scriptin kapsamı değildir. CEKI_REVIZYONU_UYGULA işlemine
    yetkili roller uygulamadaki Onay Kuralları ekranından yönetilir.

    Script PostgreSQL içindir ve tekrar çalıştırılabilir.
*/

BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TABLE IF NOT EXISTS public."CekiRevizyonTalepleri"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjeId" integer NOT NULL,
    "AnaCekiId" integer NOT NULL,
    "TalepEdenKullaniciId" integer NOT NULL,
    "DosyaAdi" character varying(255) NOT NULL,
    "DosyaIcerigi" bytea NOT NULL,
    "DosyaSha256" character(64) NOT NULL,
    "OnizlemeJson" jsonb NOT NULL,
    "OnizlemeHash" character(64) NOT NULL,
    "OnizlemeSurumu" integer NOT NULL DEFAULT 1,
    "EklenenSatirSayisi" integer NOT NULL DEFAULT 0,
    "GuncellenenSatirSayisi" integer NOT NULL DEFAULT 0,
    "SilinenSatirSayisi" integer NOT NULL DEFAULT 0,
    "UygulananRevizyonCekiId" integer NULL,
    "UygulamaTarihi" timestamp without time zone NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone NULL,
    "CreatedBy" text NULL,
    "UpdatedBy" text NULL,
    CONSTRAINT "PK_CekiRevizyonTalepleri" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_CekiRevizyonTalepleri_DosyaIcerigi_Dolu"
        CHECK (octet_length("DosyaIcerigi") > 0),
    CONSTRAINT "CK_CekiRevizyonTalepleri_DosyaIcerigi_Boyut"
        CHECK (octet_length("DosyaIcerigi") <= 20971520),
    CONSTRAINT "CK_CekiRevizyonTalepleri_DosyaSha256_Format"
        CHECK ("DosyaSha256" ~ '^[0-9A-Fa-f]{64}$'),
    CONSTRAINT "CK_CekiRevizyonTalepleri_OnizlemeJson_Dolu"
        CHECK (jsonb_typeof("OnizlemeJson") = 'object' AND "OnizlemeJson" <> '{}'::jsonb),
    CONSTRAINT "CK_CekiRevizyonTalepleri_OnizlemeJson_Boyut"
        CHECK (octet_length("OnizlemeJson"::text) <= 10485760),
    CONSTRAINT "CK_CekiRevizyonTalepleri_OnizlemeHash_Format"
        CHECK ("OnizlemeHash" ~ '^[0-9A-Fa-f]{64}$'),
    CONSTRAINT "CK_CekiRevizyonTalepleri_Sayilar_NonNegative"
        CHECK
        (
            "OnizlemeSurumu" > 0 AND
            "EklenenSatirSayisi" >= 0 AND
            "GuncellenenSatirSayisi" >= 0 AND
            "SilinenSatirSayisi" >= 0
        )
);

DO $constraints$
BEGIN
    -- Marker'ın hedef revizyon çekisi silinince kaybolmaması gerekir. Scriptin
    -- daha eski bir sürümü SET NULL kurmuşsa constraint'i RESTRICT olarak yenile.
    IF EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'FK_CekiRevizyonTalepleri_Cekiler_UygulananRevizyonCekiId'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
          AND confdeltype <> 'r'
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            DROP CONSTRAINT "FK_CekiRevizyonTalepleri_Cekiler_UygulananRevizyonCekiId";
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'FK_CekiRevizyonTalepleri_Projeler_ProjeId'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "FK_CekiRevizyonTalepleri_Projeler_ProjeId"
            FOREIGN KEY ("ProjeId")
            REFERENCES public."Projeler" ("Id")
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'CK_CekiRevizyonTalepleri_DosyaIcerigi_Dolu'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "CK_CekiRevizyonTalepleri_DosyaIcerigi_Dolu"
            CHECK (octet_length("DosyaIcerigi") > 0);
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'CK_CekiRevizyonTalepleri_DosyaIcerigi_Boyut'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "CK_CekiRevizyonTalepleri_DosyaIcerigi_Boyut"
            CHECK (octet_length("DosyaIcerigi") <= 20971520);
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'CK_CekiRevizyonTalepleri_DosyaSha256_Format'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "CK_CekiRevizyonTalepleri_DosyaSha256_Format"
            CHECK ("DosyaSha256" ~ '^[0-9A-Fa-f]{64}$');
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'CK_CekiRevizyonTalepleri_OnizlemeJson_Dolu'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "CK_CekiRevizyonTalepleri_OnizlemeJson_Dolu"
            CHECK (jsonb_typeof("OnizlemeJson") = 'object' AND "OnizlemeJson" <> '{}'::jsonb);
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'CK_CekiRevizyonTalepleri_OnizlemeJson_Boyut'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "CK_CekiRevizyonTalepleri_OnizlemeJson_Boyut"
            CHECK (octet_length("OnizlemeJson"::text) <= 10485760);
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'CK_CekiRevizyonTalepleri_OnizlemeHash_Format'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "CK_CekiRevizyonTalepleri_OnizlemeHash_Format"
            CHECK ("OnizlemeHash" ~ '^[0-9A-Fa-f]{64}$');
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'CK_CekiRevizyonTalepleri_Sayilar_NonNegative'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "CK_CekiRevizyonTalepleri_Sayilar_NonNegative"
            CHECK
            (
                "OnizlemeSurumu" > 0 AND
                "EklenenSatirSayisi" >= 0 AND
                "GuncellenenSatirSayisi" >= 0 AND
                "SilinenSatirSayisi" >= 0
            );
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'FK_CekiRevizyonTalepleri_Cekiler_AnaCekiId'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "FK_CekiRevizyonTalepleri_Cekiler_AnaCekiId"
            FOREIGN KEY ("AnaCekiId")
            REFERENCES public."Cekiler" ("Id")
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'FK_CekiRevizyonTalepleri_Kullanicilar_TalepEdenKullaniciId'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "FK_CekiRevizyonTalepleri_Kullanicilar_TalepEdenKullaniciId"
            FOREIGN KEY ("TalepEdenKullaniciId")
            REFERENCES public."Kullanicilar" ("Id")
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS
    (
        SELECT 1
        FROM pg_catalog.pg_constraint
        WHERE conname = 'FK_CekiRevizyonTalepleri_Cekiler_UygulananRevizyonCekiId'
          AND conrelid = 'public."CekiRevizyonTalepleri"'::regclass
    ) THEN
        ALTER TABLE public."CekiRevizyonTalepleri"
            ADD CONSTRAINT "FK_CekiRevizyonTalepleri_Cekiler_UygulananRevizyonCekiId"
            FOREIGN KEY ("UygulananRevizyonCekiId")
            REFERENCES public."Cekiler" ("Id")
            ON DELETE RESTRICT;
    END IF;
END;
$constraints$;

CREATE INDEX IF NOT EXISTS "IX_CekiRevizyonTalepleri_ProjeId_CreatedDate"
    ON public."CekiRevizyonTalepleri" ("ProjeId", "CreatedDate" DESC);

CREATE INDEX IF NOT EXISTS "IX_CekiRevizyonTalepleri_TalepEdenKullaniciId_CreatedDate"
    ON public."CekiRevizyonTalepleri" ("TalepEdenKullaniciId", "CreatedDate" DESC);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_CekiRevizyonTalepleri_UygulananRevizyonCekiId"
    ON public."CekiRevizyonTalepleri" ("UygulananRevizyonCekiId")
    WHERE "UygulananRevizyonCekiId" IS NOT NULL;

COMMIT;
