/*
    Lookup durumlarından bağımsız operasyonların onay zorunluluğunu kalıcı
    olarak yönetir. Onaycı rol atamaları mevcut "OnayIslemYetkileri" tablosunda
    kalır; bu script rol veya mevcut iş kuralı verisini değiştirmez.

    Sandık/Proje kilidi açma operasyonları her zaman onayda kalır ve bu tabloya
    eklenmez. CEKI_REVIZYONU_UYGULA güvenli varsayılan olarak onay gerektirir.

    PostgreSQL içindir ve tekrar çalıştırılabilir.
*/

BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS public."OnayOperasyonKurallari"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IslemKodu" character varying(100) NOT NULL,
    "OnayGerektirirMi" boolean NOT NULL DEFAULT TRUE,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone NULL,
    "CreatedBy" text NULL,
    "UpdatedBy" text NULL,
    CONSTRAINT "PK_OnayOperasyonKurallari" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_OnayOperasyonKurallari_IslemKodu_Dolu"
        CHECK (length(btrim("IslemKodu")) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_OnayOperasyonKurallari_IslemKodu"
    ON public."OnayOperasyonKurallari" ("IslemKodu");

INSERT INTO public."OnayOperasyonKurallari"
(
    "IslemKodu",
    "OnayGerektirirMi",
    "CreatedDate",
    "CreatedBy"
)
VALUES
(
    'CEKI_REVIZYONU_UYGULA',
    TRUE,
    CURRENT_TIMESTAMP,
    '20260721_OnayOperasyonKurallari.sql'
)
ON CONFLICT ("IslemKodu") DO NOTHING;

COMMIT;
