-- Üretim U1–U6. Önce 20260919_02_Uretim_Onizleme.sql çalıştırılıp sonuçlar arşivlenir.
-- Bu sürüm legacy miktarları, tarihleri, kararları, PO/fatura snapshot'larını DEĞİŞTİRMEZ.
-- Deployment migration alternatifi olarak DBA tarafından uygulanır; uygulama sırasında çalıştırılmaz.
BEGIN;
CREATE TABLE IF NOT EXISTS "AmbalajUretimFormuSurumleri" (
 "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "FormKimligi" uuid NOT NULL, "Surum" integer NOT NULL CHECK ("Surum" > 0),
 "IdempotencyAnahtari" uuid NOT NULL, "IstekHash" varchar(64) NOT NULL,
 "KapsamAnahtari" varchar(200) NOT NULL, "ProjeId" integer NULL REFERENCES "Projeler"("Id") ON DELETE RESTRICT,
 "SnapshotJson" jsonb NOT NULL, "OlusturanKullaniciId" integer NOT NULL,
 "Aciklama" varchar(1000), "CreatedDate" timestamp without time zone NOT NULL,
 "UpdatedDate" timestamp without time zone, "CreatedBy" text, "UpdatedBy" text
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AmbalajUretimFormuSurumleri_IdempotencyAnahtari" ON "AmbalajUretimFormuSurumleri"("IdempotencyAnahtari");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AmbalajUretimFormuSurumleri_FormKimligi_Surum" ON "AmbalajUretimFormuSurumleri"("FormKimligi","Surum");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AmbalajUretimFormuSurumleri_KapsamAnahtari_Surum" ON "AmbalajUretimFormuSurumleri"("KapsamAnahtari","Surum");
CREATE TABLE IF NOT EXISTS "AmbalajUretimFormuKayitlari" (
 "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "FormSurumuId" integer NOT NULL REFERENCES "AmbalajUretimFormuSurumleri"("Id") ON DELETE RESTRICT,
 "AmbalajUretimKaydiId" integer NOT NULL REFERENCES "AmbalajUretimKayitlari"("Id") ON DELETE RESTRICT,
 "CreatedDate" timestamp without time zone NOT NULL, "UpdatedDate" timestamp without time zone,
 "CreatedBy" text, "UpdatedBy" text
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AmbalajUretimFormuKayitlari_FormSurumuId_AmbalajUretimKaydiId" ON "AmbalajUretimFormuKayitlari"("FormSurumuId","AmbalajUretimKaydiId");
CREATE TABLE IF NOT EXISTS "AmbalajUretimGerceklesmeleri" (
 "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "GerceklesmeKimligi" uuid NOT NULL, "Surum" integer NOT NULL CHECK ("Surum" > 0),
 "OncekiSurumId" integer NULL REFERENCES "AmbalajUretimGerceklesmeleri"("Id") ON DELETE RESTRICT,
 "AmbalajUretimKaydiId" integer NOT NULL REFERENCES "AmbalajUretimKayitlari"("Id") ON DELETE RESTRICT,
 "IsAkisKimligi" uuid NOT NULL, "GerceklesmeTarihi" timestamp without time zone NOT NULL,
 "ProjeId" integer, "ProjeNo" varchar(100) NOT NULL, "ProjeAdi" varchar(250),
 "SandikNo" varchar(100) NOT NULL, "SandikAdi" varchar(250), "SandikCinsi" integer NOT NULL,
 "Tur" integer NOT NULL, "Adet" integer NOT NULL CHECK ("Adet" > 0),
 "Boy" numeric(18,4) NOT NULL, "En" numeric(18,4) NOT NULL, "Yukseklik" numeric(18,4) NOT NULL,
 "NetM3" numeric(18,6), "SarfM3" numeric(18,6), "FormulVersiyonu" varchar(50) NOT NULL,
 "KullaniciId" integer NOT NULL, "Gerekce" varchar(1000),
 "CreatedDate" timestamp without time zone NOT NULL, "UpdatedDate" timestamp without time zone,
 "CreatedBy" text, "UpdatedBy" text
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AmbalajUretimGerceklesmeleri_GerceklesmeKimligi_Surum" ON "AmbalajUretimGerceklesmeleri"("GerceklesmeKimligi","Surum");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AmbalajUretimGerceklesmeleri_AmbalajUretimKaydiId_Surum" ON "AmbalajUretimGerceklesmeleri"("AmbalajUretimKaydiId","Surum");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AmbalajUretimGerceklesmeleri_OncekiSurumId" ON "AmbalajUretimGerceklesmeleri"("OncekiSurumId") WHERE "OncekiSurumId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_AmbalajUretimGerceklesmeleri_GerceklesmeTarihi" ON "AmbalajUretimGerceklesmeleri"("GerceklesmeTarihi");
-- xmin PostgreSQL'in sistem kolonudur; Version adında fiziksel kolon oluşturulmaz.
ALTER TABLE "AmbalajUretimKayitlari" DROP CONSTRAINT IF EXISTS "CK_AmbalajUretimKayitlari_UretimSecimi";
ALTER TABLE "AmbalajUretimKayitlari" ADD CONSTRAINT "CK_AmbalajUretimKayitlari_UretimSecimi" CHECK (
 NOT "UretimeAlindi" OR ("AmbalajaDahil" AND ("M3Override" IS NOT NULL OR ("Adet" > 0 AND CASE
 WHEN "SandikCinsi" IN (1,2) AND NOT "BagimsizKayitMi" AND "KaynakKayitId" IS NOT NULL AND "KaynakModul" IN (1,2,3)
 THEN "Boy" > 92 AND "En" > 92 AND "Yukseklik" > 255 ELSE "Boy" > 0 AND "En" > 0 AND "Yukseklik" > 0 END)))) NOT VALID;
ALTER TABLE "AmbalajUretimKayitlari" VALIDATE CONSTRAINT "CK_AmbalajUretimKayitlari_UretimSecimi";
-- Adı farklılaşmış eski FK'lar dahil yalnız hedef audit ilişkisi değiştirilir.
DO $$ DECLARE fk record; BEGIN
 FOR fk IN SELECT conname FROM pg_constraint WHERE conrelid='"AmbalajUretimHareketleri"'::regclass AND confrelid='"AmbalajUretimKayitlari"'::regclass LOOP
 EXECUTE format('ALTER TABLE "AmbalajUretimHareketleri" DROP CONSTRAINT %I',fk.conname);
 END LOOP;
 ALTER TABLE "AmbalajUretimHareketleri" ADD CONSTRAINT "FK_AmbalajUretimHareketleri_UretimKaydi" FOREIGN KEY ("AmbalajUretimKaydiId") REFERENCES "AmbalajUretimKayitlari"("Id") ON DELETE RESTRICT;
END $$;
-- Lookup 3 başka anlamda kullanılıyorsa sessizce yeniden adlandırılmaz.
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM "LookupSandikTipleri" WHERE "Id"=3 AND "Deger"<>'Kontrplak Sandık') THEN
 RAISE EXCEPTION 'Sandık tipi 3 mevcut başka anlama sahip; eşleme incelemesi gerekli'; END IF;
END $$;
INSERT INTO "LookupSandikTipleri"("Id","Anahtar","Deger","CreatedDate")
VALUES (3,3,'Kontrplak Sandık',CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Istanbul') ON CONFLICT("Id") DO NOTHING;
COMMIT;
