-- 2026-09-19 / 04 / üretim-finans granular izin geçişi.
-- Uygulama DB'sinde otomatik çalışmaz. Yedek alınarak sürümlü dağıtım adımında uygulanır.
-- Tekrar çalıştırma sonradan kaldırılmış izinleri yeniden vermez.
BEGIN;

CREATE TABLE IF NOT EXISTS "KullaniciYetkileri" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "KullaniciId" integer NOT NULL REFERENCES "Kullanicilar"("Id") ON DELETE CASCADE,
  "MenuTanimiId" integer NOT NULL REFERENCES "MenuTanimlari"("Id") ON DELETE RESTRICT,
  "IzinVerildi" boolean NOT NULL,
  "CreatedDate" timestamp without time zone NOT NULL,
  "UpdatedDate" timestamp without time zone NULL,
  "CreatedBy" text NULL, "UpdatedBy" text NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_KullaniciYetkileri_KullaniciId_MenuTanimiId"
  ON "KullaniciYetkileri"("KullaniciId","MenuTanimiId");
CREATE INDEX IF NOT EXISTS "IX_KullaniciYetkileri_MenuTanimiId" ON "KullaniciYetkileri"("MenuTanimiId");

CREATE TABLE IF NOT EXISTS "YetkiDegisiklikleri" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AktorKullaniciId" integer NOT NULL,
  "HedefTuru" varchar(30) NOT NULL, "HedefId" integer NOT NULL,
  "OncekiDeger" text NOT NULL, "YeniDeger" text NOT NULL,
  "CreatedDate" timestamp without time zone NOT NULL,
  "UpdatedDate" timestamp without time zone NULL,
  "CreatedBy" text NULL, "UpdatedBy" text NULL
);
CREATE INDEX IF NOT EXISTS "IX_YetkiDegisiklikleri_HedefTuru_HedefId_CreatedDate"
  ON "YetkiDegisiklikleri"("HedefTuru","HedefId","CreatedDate");
CREATE TABLE IF NOT EXISTS "GranularYetkiGecisleri" ("Kod" text PRIMARY KEY, "Tarih" timestamp without time zone NOT NULL);

CREATE TEMP TABLE granular_yetki_katalogu (
  id integer PRIMARY KEY, kod text NOT NULL, ad text NOT NULL,
  parent_id integer NOT NULL, gereken integer NOT NULL, kritik boolean NOT NULL
) ON COMMIT DROP;
INSERT INTO granular_yetki_katalogu VALUES
  (5000,'yetki-atama','Rol ve kişisel izin atama',12,3,true),
  (5100,'ambalaj-kayit-duzenle','Kayıt düzenleme',46,3,false),
  (5101,'ambalaj-rapor-goruntule','Rapor görüntüleme',46,2,false),
  (5102,'ambalaj-m3-goruntule','Üretim m³ görüntüleme',46,2,false),
  (5103,'ambalaj-sarf-goruntule','Sarf görüntüleme',46,2,false),
  (5104,'ambalaj-kaynak-goruntule','Kaynak görüntüleme',46,2,false),
  (5105,'ambalaj-m3-duzenle','m³ değiştirme',46,3,true),
  (5106,'ambalaj-sarf-duzenle','Sarf değiştirme',46,3,true),
  (5107,'ambalaj-kaynak-senkronize','Kaynak eşitleme',46,3,false),
  (5108,'ambalaj-uretime-al','Üretime alma',46,3,false),
  (5109,'ambalaj-uretimden-cikar','Üretimden çıkarma',46,3,true),
  (5110,'ambalaj-dahil-et','Yapılır seçme',46,3,false),
  (5111,'ambalaj-haric-tut','Yapılmaz seçme',46,3,false),
  (5112,'ambalaj-ilave-olustur','İlave kayıt ekleme',46,3,false),
  (5113,'ambalaj-saha-olustur','Saha kaydı ekleme',46,3,false),
  (5114,'ambalaj-yedek-olustur','Yedek kayıt ekleme',46,3,false),
  (5115,'ambalaj-ic-olustur','İç sandık ekleme',46,3,false),
  (5116,'ambalaj-diger-olustur','Diğer kayıt ekleme',46,3,false),
  (5117,'ambalaj-manuel-proje','Manuel proje ekleme',46,3,false),
  (5118,'ambalaj-tur-duzenle','Kullanım türü değiştirme',46,3,true),
  (5119,'ambalaj-cins-duzenle','Fiziksel cins değiştirme',46,3,true),
  (5120,'ambalaj-proje-duzenle','Proje bağlantısı değiştirme',46,3,true),
  (5121,'ambalaj-olcu-duzenle','Ölçü değiştirme',46,3,false),
  (5122,'ambalaj-talep-duzenle','Talep bilgisi değiştirme',46,3,false),
  (5123,'ambalaj-durum-duzenle','Üretim durumu değiştirme',46,3,false),
  (5124,'ambalaj-iptal','Kayıt iptal etme',46,3,true),
  (5125,'ambalaj-geri-yukle','İptal edilmiş kaydı geri yükleme',46,3,true),
  (5126,'ambalaj-kaynak-mudahalesi','Kaynak kaydına müdahale',46,3,true),
  (5127,'ambalaj-form-goruntule','Üretim formu görüntüleme',46,2,false),
  (5128,'ambalaj-form-indir','Üretim formu PDF alma',46,2,false),
  (5129,'ambalaj-excel-indir','Excel dışarı aktarma',46,2,false),
  (5130,'ambalaj-pdf-indir','PDF dışarı aktarma',46,2,false),
  (5131,'ambalaj-form-olustur','İlk üretim formu oluşturma',46,3,false),
  (5132,'ambalaj-form-yeniden-olustur','Yeni form sürümü oluşturma',46,3,true),
  (5133,'ambalaj-uretimi-tamamla','Üretimi tamamlama',46,3,false),
  (5134,'ambalaj-uretimi-yeniden-ac','Tamamlanan üretimi açma',46,3,true),
  (5135,'ambalaj-durumu-geri-al','Üretim durumunu geri alma',46,3,true),
  (5136,'ambalaj-kritik-veri-duzenle','Kritik üretim verisi değiştirme',46,3,true),
  (5137,'ambalaj-form-sonrasi-secim-degistir','İlk form sonrası Yapılır/Yapılmaz',46,3,true),
  (5138,'ambalaj-tamamlanan-projeye-ekle','Tamamlanan projeye üretim ekleme',46,3,true),
  (5139,'ambalaj-olcu-goruntule','Ölçü görüntüleme',46,2,false),
  (5140,'ambalaj-plan-goruntule','Ambalaj planı görüntüleme',46,2,false),
  (5141,'ambalaj-plan-olustur','Ambalaj planı oluşturma',46,3,false),
  (5142,'ambalaj-bekleyen-goruntule','Bekleyen üretimleri görüntüleme',46,2,false),
  (5143,'ambalaj-uretimde-goruntule','Üretimde listesini görüntüleme',46,2,false),
  (5144,'ambalaj-tamamlanan-goruntule','Tamamlanan üretimleri görüntüleme',46,2,false),
  (5145,'ambalaj-gerceklesme-duzelt','Üretim gerçekleşmesini düzeltme',46,3,true),
  (5146,'ambalaj-gecmis-goruntule','Üretim geçmişi görüntüleme',46,2,false),
  (5147,'ambalaj-proje-detay-goruntule','Üretim proje detayı',46,2,false),
  (5148,'ambalaj-sandik-listesi-goruntule','Üretim sandık listesi',46,2,false),
  (5149,'ambalaj-m3-rapor-goruntule','m³ raporu görüntüleme',46,2,false),
  (5150,'ambalaj-kayit-ekle','Üretim kaydı ekleme',46,3,false),
  (5151,'ambalaj-kayit-sil','Üretim kaydı silme',46,3,true),
  (5200,'finans-gelir-goruntule','Gelir görüntüleme',47,2,false),
  (5201,'finans-gider-goruntule','Gider görüntüleme',47,2,false),
  (5202,'finans-gider-yonet','Gider yönetimi ekranı',47,2,false),
  (5203,'finans-siparis-goruntule','Sipariş görüntüleme',47,2,false),
  (5204,'finans-fatura-yonet','Fatura yönetimi',47,3,false),
  (5205,'finans-tarife-yonet','Tarife yönetimi',47,3,false),
  (5206,'finans-rapor-goruntule','Finans raporu görüntüleme',47,2,false),
  (5207,'finans-is-ekle','Finans işi ekleme',47,3,false),
  (5208,'finans-is-duzenle','Finans işi düzenleme',47,3,false),
  (5209,'finans-is-iptal','Finans işi iptali',47,3,true),
  (5210,'finans-tarih-degistir','Finans tarihi değiştirme',47,3,true),
  (5211,'finans-po-gir','Sipariş açma',47,3,false),
  (5212,'finans-po-degistir','Sipariş değiştirme',47,3,true),
  (5213,'finans-birim-fiyat-goruntule','Birim fiyat görüntüleme',47,2,false),
  (5214,'finans-birim-fiyat-degistir','Birim fiyat değiştirme',47,3,true),
  (5215,'finans-karlilik-goruntule','Kârlılık ve oran görüntüleme',47,2,false),
  (5216,'finans-excel-aktar','Finans Excel dışarı aktarma',47,2,false),
  (5217,'finans-pdf-aktar','Finans PDF dışarı aktarma',47,2,false),
  (5218,'finans-gider-ekle','Gider ekleme',47,3,false),
  (5219,'finans-gider-duzenle','Gider düzenleme',47,3,false),
  (5220,'finans-gider-kutuphanesi-yonet','Gider kategori yönetimi',47,3,false),
  (5221,'finans-is-kutuphanesi-yonet','İş kütüphanesi yönetimi',47,3,false),
  (5222,'finans-duzenli-is-yonet','Düzenli iş yönetimi',47,3,false),
  (5223,'finans-parasal-veri-goruntule','Parasal veri ana izni',47,2,false),
  (5224,'finans-tutar-goruntule','Net/KDV/brüt tutar görüntüleme',47,2,false),
  (5225,'finans-kayit-goruntule','Finans kayıtlarını görüntüleme',47,2,false),
  (5226,'finans-fatura-gir','Fatura girişi',47,3,false),
  (5227,'finans-fatura-degistir','Fatura değiştirme',47,3,true),
  (5228,'finans-fatura-iptal','Fatura iptali',47,3,true),
  (5229,'finans-po-iptal','Sipariş iptali',47,3,true),
  (5230,'finans-gider-iptal','Gider iptali',47,3,true),
  (5231,'finans-kalici-sil','Finans kaydını kalıcı silme',47,3,true),
  (5232,'finans-belge-yukle','PDF belge yükleme',47,3,false),
  (5233,'finans-belge-indir','PDF belge indirme',47,2,false),
  (5234,'finans-sablon-yonet','Özel iş şablonu yönetimi',47,3,false),
  (5235,'finans-denetim-gor','Finans değişiklik geçmişi',47,2,false),
  (5236,'finans-fiyatlandirma-degistir','Fiyatlandırma değiştirme',47,3,true);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM granular_yetki_katalogu k JOIN "MenuTanimlari" m
      ON (m."Id" = k.id OR m."Kod" = k.kod)
    WHERE m."Id" <> k.id OR m."Kod" <> k.kod
  ) THEN
    RAISE EXCEPTION 'Granular izin ID/kod çakışması var; mevcut menü eşlemesini inceleyin.';
  END IF;
END $$;

INSERT INTO "MenuTanimlari" ("Id","Kod","LabelKey","Icon","Route","Sira","ParentId","CreatedDate")
SELECT id,kod,ad,'',NULL,id,parent_id,CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Istanbul'
FROM granular_yetki_katalogu
ON CONFLICT ("Kod") DO UPDATE SET "LabelKey"=EXCLUDED."LabelKey","ParentId"=EXCLUDED."ParentId";

-- İlk geçiş: eski R/W görünüm erişimini korur; W yalnız kritik olmayan yeni eylemlere taşınır.
-- Admin de bypass kullanmaz: rol 1'e açık kayıt yazılır, kişisel ret bu rolü de sınırlar.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "GranularYetkiGecisleri" WHERE "Kod"='20260919-granular-v1') THEN
    INSERT INTO "RolYetkileri" ("RolId","MenuTanimiId","YetkiTipiId","CreatedDate")
    SELECT 1,m."Id",2,CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Istanbul'
    FROM "MenuTanimlari" m WHERE m."Id" IN (46,47) AND EXISTS (SELECT 1 FROM "Roller" WHERE "Id"=1)
    ON CONFLICT ("RolId","MenuTanimiId") DO NOTHING;
    INSERT INTO "RolYetkileri" ("RolId","MenuTanimiId","YetkiTipiId","CreatedDate")
    SELECT r."Id",k.id,k.gereken,CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Istanbul'
    FROM "Roller" r CROSS JOIN granular_yetki_katalogu k
    WHERE r."Id"=1 OR (
      k.id<>5000 AND NOT k.kritik AND EXISTS (
        SELECT 1 FROM "RolYetkileri" eski
        WHERE eski."RolId"=r."Id" AND eski."MenuTanimiId"=k.parent_id AND eski."YetkiTipiId">=k.gereken
      )
    )
    ON CONFLICT ("RolId","MenuTanimiId") DO NOTHING;
    INSERT INTO "GranularYetkiGecisleri" VALUES ('20260919-granular-v1', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Istanbul');
  END IF;
END $$;
SELECT setval(pg_get_serial_sequence('"MenuTanimlari"','Id'), GREATEST((SELECT MAX("Id") FROM "MenuTanimlari"),1));
SELECT setval(pg_get_serial_sequence('"RolYetkileri"','Id'), GREATEST((SELECT MAX("Id") FROM "RolYetkileri"),1));
COMMIT;

-- Denetim çıktısı: kritik izinler ilk atamada yalnız açık Admin seed'i ve sonradan yönetici atamasıyla bulunur.
SELECT m."Kod",r."Ad",ry."YetkiTipiId"
FROM "RolYetkileri" ry JOIN "MenuTanimlari" m ON m."Id"=ry."MenuTanimiId"
JOIN "Roller" r ON r."Id"=ry."RolId"
WHERE m."Id" BETWEEN 5000 AND 5299 ORDER BY m."Kod",r."Ad";
