-- Yeni API sürümünden ÖNCE çalıştırılır. Mevcut iş verisine dokunmaz.
-- Güncelleme ve sıfır kurulum: mevcut temel şema kurulduktan sonra bu script uygulanır.
-- İstek anahtarı defteri içerik silinse de ağ tekrarını tanır; kimlikler snapshot olduğu için FK değildir.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

CREATE TABLE IF NOT EXISTS public."SandikTopluTasimaIslemleri"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_SandikTopluTasimaIslemleri" PRIMARY KEY,
    "IslemAnahtari" uuid NOT NULL,
    "IstekHash" character varying(64) NOT NULL,
    "KullaniciId" integer NOT NULL,
    "ProjeId" integer NOT NULL,
    "KaynakSandikId" integer NOT NULL,
    "HedefSandikId" integer NOT NULL,
    "SatirSayisi" integer NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "UpdatedDate" timestamp without time zone NULL,
    "CreatedBy" text NULL,
    "UpdatedBy" text NULL,
    CONSTRAINT "CK_SandikTopluTasimaIslemleri_SatirSayisi" CHECK ("SatirSayisi" BETWEEN 1 AND 250)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_SandikTopluTasimaIslemleri_IslemAnahtari"
    ON public."SandikTopluTasimaIslemleri" ("IslemAnahtari");
CREATE INDEX IF NOT EXISTS "IX_SandikTopluTasimaIslemleri_ProjeId_CreatedDate"
    ON public."SandikTopluTasimaIslemleri" ("ProjeId", "CreatedDate");

DO $verify$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_index i
        JOIN pg_class c ON c.oid = i.indexrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname = 'IX_SandikTopluTasimaIslemleri_IslemAnahtari'
          AND i.indisunique AND i.indisvalid
    ) THEN
        RAISE EXCEPTION 'Toplu taşıma idempotency benzersiz index doğrulaması başarısız.';
    END IF;
END
$verify$;
COMMIT;
